name: 'GitHub Actions Weather Bot'

on:
  push:
  workflow_dispatch:
  schedule:
    - cron: '0 1 * * *'

jobs:
  bot:
    runs-on: ubuntu-latest
    steps:
      - name: 'Checkout codes'
        uses: actions/checkout@v1

      - name: 'Get Date'
        run: echo "REPORT_DATE=$(TZ=':Asia/Shanghai' date '+%Y-%m-%d %T')"


      - name: 'Set up Node.js'
        uses: actions/setup-node@v3
        with:
          node-version: 14

      - name: 'Install dependencies'   
        run: npm install

      - name: 'RUN APP'
        run: node main.js
        env:
          USER_NAME: ${{ secrets.MAIL_USERNAME }}
          PASS_WORD: ${{ secrets.MAIL_PASSWORD }}



